services:
  comfyui:
    image: saladtechnologies/comfyui:dynamic
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    ports:
      - "8188:8188"
    volumes:
      - models:/opt/ComfyUI/models
      - output:/opt/ComfyUI/output
    # environment:
    #   LOAD_SDXL_BASE: 1
    #   LOAD_REFINER: 1
    #   CKPT_URLS: https://civitai.com/api/download/models/114367?type=Model&format=SafeTensor&size=full&fp=fp16

volumes:
  models:
    driver: local
    driver_opts:
      type: none
      device: ./models
      o: bind
  output:
    driver: local
    driver_opts:
      type: none
      device: ./output
      o: bind