#! /usr/bin/env bash
set -e

# This script is executed by the Dockerfile entrypoint. It looks for these environment variables,
# and if they are set, it will use them to download a model from Civit.ai or Huggingface respectively,
# and then run the model server.
# CIVITAI_MODEL_VERSION_ID: abc
# LOAD_REFINER: 1 | 0

LOAD_ONLY=${LOAD_ONLY:-0}

models_dir=/opt/ComfyUI/models
checkpoints_dir=${models_dir}/checkpoints/
vae_dir=${models_dir}/vae/
loras_dir=${models_dir}/loras/
upscale_dir=${models_dir}/upscale_models/
controlnet_dir=${models_dir}/controlnet/
extension_dir=/opt/ComfyUI/custom_nodes/

mkdir -p $checkpoints_dir
mkdir -p $vae_dir
mkdir -p $loras_dir
mkdir -p $upscale_dir
mkdir -p $controlnet_dir
mkdir -p $extension_dir

manifest=$(./configure --ckpt-path $checkpoints_dir --vae-path $vae_dir --lora-path $loras_dir --controlnet-model-path $controlnet_dir --extension-path $extension_dir)
echo $manifest

#
if [ "$LOAD_ONLY" == "1" ]; then
  echo "Exiting after loading models"
  exit 0
fi

export IP=${IP:-$HOST}
export COMFYUI_PORT=${COMFYUI_PORT:-$PORT}

init.sh
